# Generated by Django 5.2.17 on 2026-09-08 03:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('access', '0002_comment'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='submission',
            name='claim',
        ),
        migrations.AlterField(
            model_name='confirmation',
            name='vote',
            field=models.CharField(choices=[('ACCESSIBLE', 'Accessible'), ('NOT_ACCESSIBLE', 'Not Accessible')], max_length=14),
        ),
        migrations.AddConstraint(
            model_name='submission',
            constraint=models.UniqueConstraint(fields=('venue', 'feature'), name='unique_submission_per_venue_feature'),
        ),
    ]
